#!/bin/sh
# Init script for aesdsocket daemon
# Installed as /etc/init.d/S99aesdsocket

case "$1" in
    start)
        echo "Starting aesdsocket daemon..."
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket daemon..."
        start-stop-daemon -K -n aesdsocket
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
