#!/bin/sh
# Simple shell script that counts the number of files within a directory and all of its children, and also reports how many times a specified phrase appears in said directory.
# Author: Jack Napoli
# Disclosure: All documentation comments written in this file were generated by Jack Napoli. All code in this file was written with the assistance of Claude Code, and reviewed by Jack Napoli
# for both correctness and optimal process.
# Claude Code Chats: https://gist.github.com/jsnapoli1/a18789824a3dfd1ba5eb8d1dc83845ca

# INVOKATION:
# This command is used as follows:
# finder.sh <arg1> <arg2>
# Full Example: finder.sh /tmp/aesd/assignment1 linux

# ARGUMENTS:
# <arg1>
    # Variable Name: filesdir
    # Type: String
    # Purpose: The path to the directory that should be searched
    # Example: /tmp/aesd/assignment1
# <arg2>
    # Variable Name: searchstr
    # Type: string
    # Purpose: The text string that shall be searched for within the specified directory
    # Example "hello, world"

# ERROR CASES:
# Program shall return an error value 1 in the event that:
    # 1. If any of the above parameters are not specified
    # 2. If filesdir does not represent a proper directory on the filesystem

# Store arguments in variables
filesdir=$1
searchstr=$2

# Check if both arguments are provided
# if the number of arguments doesn't equal two, print error, exit 1
if [ $# -ne 2 ]; then
    echo "Error: Two arguments required."
    echo "Usage: finder.sh <filesdir> <searchstr>"
    exit 1
fi

# Check if filesdir is a valid directory
# if the directory doesn't exist, print error, exit 1
if [ ! -d "$filesdir" ]; then
    echo "Error: $filesdir is not a directory."
    exit 1
fi

# Count the number of files in the directory and subdirectories
# find the number of files (items of type f) in filesdir, and  then count the number of lines with wc
# save it as a variable numfiles
num_files=$(find "$filesdir" -type f | wc -l)

# Count the number of matching lines containing searchstr
# print every time in grep that the searchstr appears, count the number of lines, save variable
num_matches=$(grep -r "$searchstr" "$filesdir" 2>/dev/null | wc -l)

echo "The number of files are $num_files and the number of matching lines are $num_matches"
